services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - api
      - frontend
  
  auth:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env
    healthcheck:
      test: ["CMD", "curl","-f","http://0.0.0.0:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  

  api:
    build: ./api-service
    container_name: api_service
    ports:
      - "5000:5000"
    depends_on:
      - auth
    env_file:
      - ./api-service/.env
    healthcheck:
      test: ["CMD", "curl","-f","http://0.0.0.0:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 
  
  frontend:
    build: ./frontend
    container_name: frontend_ui
    ports:
      - "3000:3000"
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo-data: